### ISSUE TITLE
Issue running graftm create using docker

### ISSUE THREAD

**Issue by erins1** [geronimp/graftM-docker#5]
Hi,

I am a new user of graftM. Running using docker. 
When I try to run graftM create to build a package I receive the following errors.

`> docker run -v `pwd`:/data wwood/graftm:v0.13.1 create --sequences /Users/e/Documents/graftm_test/bsh_sequences.fasta --taxonomy /Users/e/Documents/graftm_test/bsh_taxonomy_file2.txt --output bsh_graftm_package.gpkg --log bsh_log.txt
`
Traceback (most recent call last):
  File "/gnu/store/jcxdrw6c6z7n9q9wwqjyirk0lxgm715x-graftm-0.13.1/bin/.graftM-real", line 415, in <module>
    Run(args).main()
  File "/gnu/store/jcxdrw6c6z7n9q9wwqjyirk0lxgm715x-graftm-0.13.1/lib/python3.7/site-packages/graftm/run.py", line 681, in main
    threads = self.args.threads
  File "/gnu/store/jcxdrw6c6z7n9q9wwqjyirk0lxgm715x-graftm-0.13.1/lib/python3.7/site-packages/graftm/create.py", line 593, in main
    taxonomy_definition = GreenGenesTaxonomy.read_file(taxonomy).taxonomy
  File "/gnu/store/jcxdrw6c6z7n9q9wwqjyirk0lxgm715x-graftm-0.13.1/lib/python3.7/site-packages/graftm/greengenes_taxonomy.py", line 51, in read_file
    with open(input_filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/e/Documents/graftm_test/bsh_taxonomy_file2.txt'

Even though the file clearly is in my current working directory:
 Directory: C:\Users\e\Documents\graftm_test> ls
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        28/10/2020  10:48 AM         214479 bsh_sequences.fasta
-a----        28/10/2020  12:05 PM          27362 bsh_taxonomy_file1.txt
-a----        28/10/2020   1:55 PM          27362 bsh_taxonomy_file2.txt

Happens whether I run this on PC or MAC.

Including `--user $(id -u):$(id -g) ` doesn't change anything other than generating the additional error "The term 'id' is not recognized as the name of a cmdlet, function, script file, or operable program."

Thanks for any help in understanding how to overcome this error.
Erin

**Comment by wwood** [comment]
See https://github.com/geronimp/graftM/issues/268

**Comment by wwood** [comment]
I cannot close this issue, but it probably should be in favour of the above issue.
